name: TeamAnneal CI/CD Pipeline

env:
  ZONE_NAME: ${{vars.ZONE_NAME}}

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    container:
      image: node:20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p /github/home/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /github/home/.ssh/id_rsa
          chmod 600 /github/home/.ssh/id_rsa
          echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > /github/home/.ssh/config
          ssh-keyscan -t rsa github.com >> /github/home/.ssh/known_hosts
          eval $(ssh-agent)
          ssh-add /github/home/.ssh/id_rsa

      - name: Prepare build
        run: |
          cd web
          apt-get update
          npm install
          npm run build
          cd ..

      - name: Create temporary directory in /tmp
        run: mkdir /tmp/temp_dir

      - name: Copy files to temporary directory
        run: cp -r ./* /tmp/temp_dir/

      - name: Create tar archive in temporary directory
        run: cd /tmp && tar -czvf teamanneal.tar.gz ./temp_dir

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: teamanneal
          path: /tmp/temp_dir/teamanneal.tar.gz

      - name: Cleanup temporary directory
        run: rm -rf /tmp/temp_dir

      - name: Deploy to zone
        run: |
          npm install -g git+https://github.com/eait-itig/node-triton#eait
          npm install -g manta
          triton profile create -f .triton.json || true
          export MANTA_URL=https://stluc.manta.uqcloud.net
          eval $(ssh-agent)
          ssh-add /github/home/.ssh/id_rsa
          mv /tmp/teamanneal.tar.gz deploy-${{github.run_number}}.tar.gz
          mput --account=teamanneal --subuser=piper --keyId=2e:63:eb:07:60:fa:57:24:58:7e:2b:02:cd:65:cd:8c --role-tag=pipeline-roles -f deploy-${{github.run_number}}.tar.gz /teamanneal/stor/builds/
          export TARBALL="$(msign --account=teamanneal --subuser=piper --keyId=2e:63:eb:07:60:fa:57:24:58:7e:2b:02:cd:65:cd:8c --role-tag=pipeline-roles /teamanneal/stor/builds/deploy-${{github.run_number}}.tar.gz)"
          triton --act-as=teamanneal -a teamanneal -U https://cloudapi.gps-1.uqcloud.net -u piper -k 2e:63:eb:07:60:fa:57:24:58:7e:2b:02:cd:65:cd:8c inst exec $ZONE_NAME -- /bin/sh -c "cd /var/www/server && rm -rf teamanneal && mkdir teamanneal &&
                curl \"${TARBALL}\" | tar -C teamanneal/ -zxvf - &&
                cd teamanneal && mv temp_dir/* temp_dir/.* . 2>/dev/null || true && systemctl restart teamanneal"
